package Model;
// Generated 25 juil. 2015 19:43:56 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.codehaus.jackson.annotate.JsonIgnoreProperties; 

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", catalog = "ghl") 
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"}) 
public class Categories implements java.io.Serializable {

	private Integer idcategories;
	
	private String nom;

	private Set<Chambres> chambres = new HashSet<Chambres>(0);
	private Set<Saison> saison = new HashSet<Saison>(0);
	

	public Categories() {
	}
	
	
	public Categories(Integer idcategories, String nom) {
		this.idcategories=idcategories;
		
		this.nom = nom;
		
		
	}

	public Categories(Integer idcategories, String nom, Set<Chambres> chambres) {
		this.idcategories=idcategories;
		
		this.nom = nom;
		this.chambres=chambres;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idcategories", unique = true, nullable = false)
	public Integer getIdcategories() {
		return this.idcategories;
	}

	public void setIdcategories(Integer idcategories) {
		this.idcategories = idcategories;
	}

	

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}



	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "categories")
	public Set<Chambres> getChambres() {
		return this.chambres;
	}

	public void setChambres(Set<Chambres> chambres) {
		this.chambres = chambres;
	}
	
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "categories")
	public Set<Saison> getSaison() {
		return this.saison;
	}

	public void setSaison(Set<Saison> saison) {
		this.saison = saison;
	}

}
