package Model;
// Generated 25 juil. 2015 19:43:56 by Hibernate Tools 4.3.1




import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.FetchType;
import org.codehaus.jackson.annotate.JsonIgnoreProperties; 
 
/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "ghl")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})  
public class Facture implements java.io.Serializable {

	private Integer idfacture;
	private Reservation reservation;
	private Integer total;

	public Facture() {
	}

	public Facture(Integer idfacture, Integer total, Reservation reservation) {
		this.idfacture = idfacture;
		this.total = total;
		this.reservation=reservation;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "idfacture", unique = true, nullable = false)
	public Integer getIdfacture() {
		return this.idfacture;
	}

	public void setIdfacture(Integer idfacture) {
		this.idfacture = idfacture;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idreserv", nullable = false)
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation=reservation;
	}
	

	@Column(name = "total")
	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	
	

}
