package Model;
// Generated 25 juil. 2015 19:43:56 by Hibernate Tools 4.3.1
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.codehaus.jackson.annotate.JsonIgnoreProperties; 

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name = "hotel", catalog = "ghl")

public class Hotel implements java.io.Serializable {

	private Integer idhotel;
	private String nomhotel;
	private String ville;
	private Integer nbretoile;
	private Integer offre;
	private Integer nbreserv;
	private Integer nbchambre;
	
	private Set<Chambres> chambres = new HashSet<Chambres>(0);
	public Hotel() {
	}

	public Hotel(Integer idhotel, String nomhotel, String ville, Integer nbretoile, Integer offre, Integer nbreserv) {
		this.idhotel=idhotel;
		this.nomhotel = nomhotel;
		this.ville = ville;
		this.nbretoile = nbretoile;
		this.offre = offre;
		this.nbreserv = nbreserv;
	}
	
	
	public Hotel(Integer idhotel, String nomhotel, String ville, Integer nbretoile, Integer offre, Integer nbreserv, Set<Chambres> chambres) {
		this.idhotel=idhotel;
		this.nomhotel = nomhotel;
		this.ville = ville;
		this.nbretoile = nbretoile;
		this.offre = offre;
		this.nbreserv = nbreserv;
		this.chambres=chambres;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	

	@Column(name = "idhotel", unique = true, nullable = false)
	public Integer getIdhotel() {
		return this.idhotel;
	}

	public void setIdhotel(Integer idhotel) {
		this.idhotel = idhotel;
	}

	@Column(name = "nomhotel", nullable = false, length = 50)
	public String getNomhotel() {
		return this.nomhotel;
	}

	public void setNomhotel(String nomhotel) {
		this.nomhotel = nomhotel;
	}

	@Column(name = "ville", nullable = false, length = 50)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "nbretoile", nullable = false)
	public Integer getNbretoile() {
		return this.nbretoile;
	}

	public void setNbretoile(Integer nbretoile) {
		this.nbretoile = nbretoile;
	}

	@Column(name = "offre",nullable = false)
	public Integer getOffre() {
		return this.offre;
	}

	public void setOffre(Integer offre) {
		this.offre = offre;
	}

	@Column(name = "nbreserv", nullable = false)
	public Integer getNbreserv() {
		return this.nbreserv;
	}

	public void setNbreserv(Integer nbreserv) {
		this.nbreserv = nbreserv;
	}
	
	
	
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "hotel")
	public Set<Chambres> getChambres() {
		return this.chambres;
	}

	public void setChambres(Set<Chambres> chambres) {
		this.chambres = chambres;
	}
	@Column(name = "nbchambre", nullable = false)
	public Integer getNbchambre() {
		return nbchambre;
	}

	public void setNbchambre(Integer nbchambre) {
		this.nbchambre = nbchambre;
	}


}
