package Model;
// Generated 25 juil. 2015 19:43:56 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.annotations.GenericGenerator; 



/**
 * Chambres generated by hbm2java
 */
@Entity
@Table(name = "prix", catalog = "ghl")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"}) 
public class Prix implements java.io.Serializable {

	private Integer idprix;
	private Integer prix;
	private Saison saison;
	
	

	public Prix() {
	}
	
	public Prix(Integer idprix, Integer prix, Saison saison) {
		this.idprix = idprix;
		this.prix = prix;
		
		this.saison = saison;
		
	}

	
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idprix", unique = true, nullable = false)
	public Integer getIdprix() {
		return this.idprix;
	}

	public void setIdprix(Integer idprix) {
		this.idprix = idprix;
	}
	
	@Column(name = "prix")
	public Integer getPrix() {
		return this.prix;
	}

	public void setPrix(Integer prix) {
		this.prix = prix;
	}

	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idsaison", nullable = false)
	public Saison getSaison() {
		return this.saison;
	}

	public void setSaison(Saison saison) {
		this.saison = saison;
	}
	
	



}
