package Model;
// Generated 25 juil. 2015 19:43:56 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
/**
 * RoleUsers generated by hbm2java
 */
@Entity
@Table(name = "role_users", catalog = "ghl")
public class RoleUsers implements java.io.Serializable {

	private int idRoleUsers;
	private Users users;
	private String role;

	public RoleUsers() {
	}

	public RoleUsers(int idRoleUsers, String role) {
		this.idRoleUsers = idRoleUsers;
		this.role = role;
	}

	public RoleUsers(int idRoleUsers, Users users, String role) {
		this.idRoleUsers = idRoleUsers;
		this.users = users;
		this.role = role;
	}

	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id_roleUsers", unique = true, nullable = false)
	public int getIdRoleUsers() {
		return this.idRoleUsers;
	}

	public void setIdRoleUsers(int idRoleUsers) {
		this.idRoleUsers = idRoleUsers;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_u", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}


	@Column(name = "role", length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
