package Model;
// Generated 25 juil. 2015 19:43:56 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.annotations.GenericGenerator; 



/**
 * Chambres generated by hbm2java
 */
@Entity
@Table(name = "saison", catalog = "ghl")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"}) 
public class Saison implements java.io.Serializable {

	private Integer idsaison;
	private String periode;
	private Date debperiode;
	private Date finperiode;
	private Categories categories;
	private Chambres chambres;
	private Set<Prix> prix = new HashSet<Prix>(0);
	

	public Saison() {
	}
	
	public Saison(Integer idsaison, String periode, Categories categories ,Chambres chambres) {
		this.idsaison=idsaison;
		this.periode = periode;
		this.categories = categories;
		this.chambres= chambres;
	}

	public Saison(Integer idsaison, String periode, Categories categories, Chambres chambres, Set<Prix> prix) {
		this.idsaison=idsaison;
		this.periode = periode;
		this.categories = categories;
		this.chambres= chambres;
		this.prix=prix;
	}
	@GenericGenerator(name = "generator", strategy = "increment")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idsaison", unique = true, nullable = false)
	public Integer getIdsaison() {
		return this.idsaison;
	}

	public void setIdsaison(Integer idsaison) {
		this.idsaison = idsaison;
	}

	@Column(name = "periode")
	public String getPeriode() {
		return this.periode;
	}

	public void setPeriode(String periode) {
		this.periode = periode;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "debperiode", length = 10)
	public Date getDebperiode() {
		return this.debperiode;
	}

	public void setDebperiode(Date debperiode) {
		this.debperiode = debperiode;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "finperiode", length = 10)
	public Date getFinperiode() {
		return this.finperiode;
	}

	public void setFinperiode(Date finperiode) {
		this.finperiode = finperiode;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idcategories", nullable = false)
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}
	
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idchambres", nullable = false)
	public Chambres getChambres() {
		return this.chambres;
	}

	public void setChambres(Chambres chambres) {
		this.chambres = chambres;
	}
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "saison")
	public Set<Prix> getPrix() {
		return this.prix;
	}

	public void setPrix(Set<Prix> prix) {
		this.prix = prix;
	}


}
